#!/bin/bash
# Define usage function
usage() {
    echo "Usage:"
    echo "  Dory -m <fileformat> -a <input1> -b <input2> -o <outputPath> -c <chrnum>   # For two conditions"
    echo "  Dory -m <fileformat> -i <inputCoordFile> -l <labelFile> -o <outputPath> -n <labelcolname> -c <chrnum>   # For more than two conditions/cell-types"
    exit 1
}
# Function to check and install R packages
#check_and_install_r_packages() {
#    packages=("ggplot2" "dplyr" "reshape2" "optparse" "future" "parallel" "furrr")  # Add your required R packages here
#    for pkg in "${packages[@]}"; do
#        Rscript -e "if (!requireNamespace('$pkg', quietly = TRUE)) install.packages('$pkg', repos='https://cran.rstudio.com/')"
#    done
#}


# Run the function to ensure required packages are installed
#check_and_install_r_packages

output="."
ctcolname="Cell_Type"
# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -a) a_value="$2"; shift 2 ;;
        -b) b_value="$2"; shift 2 ;;
        -i) i_value="$2"; mode="group"; shift 2 ;;  # If -i is present, switch to group mode
        -l) l_value="$2"; mode="group"; shift 2 ;;  # If -l is present, switch to group mode
        -o) output="$2"; shift 2 ;;
        -m) file_format="$2"; shift 2 ;;
        -c) chr_format="$2"; shift 2 ;;
        -n) ctcolname="$2"; mode="group"; shift 2 ;;
        *) echo "Unknown parameter: $1"; usage ;;
    esac
done

mkdir -p "$output"

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
# Call the appropriate R script
if [[ -n "$a_value" && -n "$b_value" && -z "$i_value" && -z "$l_value" ]]; then
    # Run single mode
    Rscript "$SCRIPT_DIR/R/Dory_single.R" -a "$a_value" -b "$b_value" -o "$output" -m "$file_format" -c "$chr_format"

elif [[ -n "$i_value" && -z "$a_value" && -z "$b_value" ]]; then
    # Run group mode 
    Rscript "$SCRIPT_DIR/R/Dory_group.R" -i "$i_value" -l "$l_value" -n "$ctcolname" -o "$output" -m "$file_format" -c "$chr_format"

else
    echo "Error: Invalid arguments. Use either:"
    echo "  -a <state1> -b <state2>   # For comparing a single pair of states"
    echo "  -i <file> -l <file>       # For comparing a group of states"
    usage
fi